/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.menu.view;

/**
 *
 * @author Leslie Titoaña LAMES Tech ESPE-DCC0
 */
public class PapersRegistration extends javax.swing.JFrame {

    /**
     * Creates new form PapersRegistration
     */
    public PapersRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        itmCreateUser = new javax.swing.JMenuItem();
        itmChangePassword = new javax.swing.JMenuItem();
        mnuPaper = new javax.swing.JMenu();
        itmGeneratePaper = new javax.swing.JMenuItem();
        itmReviewPaper = new javax.swing.JMenuItem();
        mnuLogin = new javax.swing.JMenu();
        itmListOfPapers = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuUser.setText("User");
        mnuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuUserMouseClicked(evt);
            }
        });

        itmCreateUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        itmCreateUser.setText("Create");
        itmCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCreateUserActionPerformed(evt);
            }
        });
        mnuUser.add(itmCreateUser);

        itmChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        itmChangePassword.setText("Change Password");
        itmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmChangePasswordActionPerformed(evt);
            }
        });
        mnuUser.add(itmChangePassword);

        jMenuBar1.add(mnuUser);

        mnuPaper.setText("Paper");

        itmGeneratePaper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        itmGeneratePaper.setText("Generate");
        itmGeneratePaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGeneratePaperActionPerformed(evt);
            }
        });
        mnuPaper.add(itmGeneratePaper);

        itmReviewPaper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        itmReviewPaper.setText("Review");
        itmReviewPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReviewPaperActionPerformed(evt);
            }
        });
        mnuPaper.add(itmReviewPaper);

        jMenuBar1.add(mnuPaper);

        mnuLogin.setText("Login");

        itmListOfPapers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        itmListOfPapers.setText("List of Papers");
        itmListOfPapers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListOfPapersActionPerformed(evt);
            }
        });
        mnuLogin.add(itmListOfPapers);

        jMenuBar1.add(mnuLogin);

        mnuExit.setText("Exit");
        mnuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUserMouseClicked

    private void mnuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuExitMouseClicked

    private void itmCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCreateUserActionPerformed
        FrmCreateUser frmCreateUser = new FrmCreateUser();
        frmCreateUser.setVisible(true);
    }//GEN-LAST:event_itmCreateUserActionPerformed

    private void itmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmChangePasswordActionPerformed
        FrmChangePassword frmChangePassword = new FrmChangePassword();
        frmChangePassword.setVisible(true);
    }//GEN-LAST:event_itmChangePasswordActionPerformed

    private void itmReviewPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReviewPaperActionPerformed
        FrmReviewPaper frmReviewPaper = new FrmReviewPaper();
        frmReviewPaper.setVisible(true);
    }//GEN-LAST:event_itmReviewPaperActionPerformed

    private void itmGeneratePaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGeneratePaperActionPerformed
        FrmGeneratePaper frmGeneratePaper = new FrmGeneratePaper();
        frmGeneratePaper.setVisible(true);
    }//GEN-LAST:event_itmGeneratePaperActionPerformed

    private void itmListOfPapersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListOfPapersActionPerformed
        FrmListOfPapers frmListOfPapers= new FrmListOfPapers();
        frmListOfPapers.setVisible(true);
    }//GEN-LAST:event_itmListOfPapersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PapersRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PapersRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PapersRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PapersRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PapersRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmChangePassword;
    private javax.swing.JMenuItem itmCreateUser;
    private javax.swing.JMenuItem itmGeneratePaper;
    private javax.swing.JMenuItem itmListOfPapers;
    private javax.swing.JMenuItem itmReviewPaper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenu mnuPaper;
    private javax.swing.JMenu mnuUser;
    // End of variables declaration//GEN-END:variables
}
